<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9PXThO1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9PXThO1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9PXThO1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9PXThO1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9PXThO1\App_KernelDevDebugContainer([
    'container.build_hash' => '9PXThO1',
    'container.build_id' => 'bcbc9ded',
    'container.build_time' => 1586171617,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9PXThO1');
